apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: restaurant-mysql-pv-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: restaurant-mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: restaurant-mysql
  template:
    metadata:
      labels:
        app: restaurant-mysql
    spec:
      containers:
        - name: mysql
          image: mysql:8
          env:
            - name: MYSQL_ALLOW_EMPTY_PASSWORD
              value: "yes"
          ports:
            - containerPort: 3306
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: mysql-storage
      volumes:
        - name: mysql-storage
          persistentVolumeClaim:
            claimName: restaurant-mysql-pv-claim

---
apiVersion: v1
kind: Service
metadata:
  name: restaurant-mysql-service
spec:
  selector:
    app: restaurant-mysql
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  type: ClusterIP
